### ISSUE TITLE
Could not parse application options: invalid option: --manifestdir

### ISSUE THREAD

**Issue by prayagupa** [antonyh/vagrant-tomcat#1]
I get following error on `vagrant up`.

``` bash
==> default: Complete!
==> default: Running provisioner: puppet...
==> default: Running Puppet with site.pp...
==> default: Error: Could not parse application options: invalid option: --manifestdir
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

This is the end of my log. I `ssh`ed the vagrant box, neither is tomcat running.

I updated the fedora box, as the one you are using is moved to `bento/fedora`, (my fork here -> https://github.com/prayagupd/vagrant-tomcat-puppet/commit/ec813eb1e85abc338a5582532c9bd87ac55bae5f)

**Comment by antonyh** [comment]
This looks like an issue between Vagrant and Puppet, as the manifestdir option was deprecated circa 3.6 and removed in 4.0 as far as I can tell, and so it breaks with Vagrant < 1.7.4 (ish).

What version of Vagrant are you using? Can you try updating?

**Comment by prayagupa** [comment]
I'm using `Vagrant 1.7.4`. I will try updating vagrant if that fixes the issue.

**Comment by antonyh** [comment]
It seems to work with Vagrant 1.8.1 & VirtualBox 5.0.6. I'll update here with a new JDK version, as Java 7 isn't in the repos for Fedora 21+

**Comment by prayagupa** [comment]
Sounds Great.

**Comment by antonyh** [comment]
Hi @prayagupd did you manage to get this working? We can close this if it's solved by updating Vagrant.
